### ISSUE TITLE
INCLUDE_DIRECTORIES has no effect on daq_generate_dal

### ISSUE THREAD

**Issue by gcrone** [DUNE-DAQ/oksdalgen#4]
It looks like you were a little to aggressive in cleaning up the ATLAS specific code in genconfig.cmake and config_opts_INCLUDE_DIRECTORIES is not added to the list of include directories at all. I suggest something like this which seems to work for me:

```
   if(DAQ_PROJECT_GENCONFIG_INCLUDES OR config_opts_INCLUDE_DIRECTORIES)
      set(config_includes -I ${DAQ_PROJECT_GENCONFIG_INCLUDES})
      foreach(inc ${config_opts_INCLUDE_DIRECTORIES})
         list(APPEND config_includes ${inc})
      endforeach()
    endif()

```

**Comment by jcfreeman2** [comment]
As `INCLUDE_DIRECTORIES` is no longer a valid argument to this function, I'm closing the issue.
